hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: "data/raw/5000s_member_repair.xlsx"
  processed: data/processed/processed.csv
  final: data/final/final.csv